- .goreleaser.yaml
https://goreleaser.com/customization/ko/?h=kos#signing-ko-manifests
Similar to how Chainguard did it here https://github.com/chainguard-dev/clank/blob/main/.goreleaser.yml#L56-L82
Drive-by: 
- Do not `go mod tidy`, this can mutate the `go.mod`, which is detected by Harden Runner , yay!
- Avoid building `i386`
> Make sure goreleaser uses cosign to sign images

- formatters/pretty/pretty.go
output the raw SARIF result level into the pretty print output to help contextualize the severity of the findings
> output the rule severity in pretty print

- docs/content.go
- docs/content_test.go
- formatters/sarif/sarif.go
add the docs to the SARIF output format so it looks pretty in VS Code/code scanning alerts
> add docs module and add documentation to SARIF

- .github/workflows/pop.yml
- Dockerfile.action
- action.yml
- Add GitHub Action to simplify usage of `poutine`.
- Add self-test with a pinned version
- Make sure the action can be used with a harden-runner block config
> Add GitHub Action and self-test

- opa/rego/rules/untrusted_checkout_exec.rego
- scanner/inventory_test.go
report the `run:` line if the build command is in bash script or the `uses:` line if it's an action
> fix untrusted_checkout_exec line numbers

- formatters/sarif/sarif.go
- the markdown documentation need to be in results help to show up in code scanning alerts
- help.text is set as the rule URL. it is not shown if help.markdown is set
- use the result description from before #23 because it breaks the SARIF upload to Github
> adjust sarif for github code scanning alerts

- opa/rego/poutine/utils.rego
- scanner/testdata/.github/workflows/secrets.yaml
consider any numerical versions as hosted runners. 
fix #16
> adjust self-hosted runner regex

- opa/rego/poutine/inventory/github_actions.rego
- scanner/inventory_test.go
- scanner/testdata/.github/workflows/reusable.yml
- Parse job.uses as a github actions purl and add it to the build inventory. 
- Adjust inventory/github_actions.rego with rego.v1 syntax
> add reusable workflows to the build inventory

- scanner/scanner.go
follow up on https://github.com/boostsecurityio/poutine/pull/56, add debug logs when an invalid workflow/config is encountered.
> add debug logs on workflow parsing errors

- models/config.go
- opa/opa.go
- opa/opa_test.go
- opa/rego/poutine/queries/findings.rego
- scanner/inventory_test.go
- Allow the OPA instance to be configured to skip rules and findings.
- Make `print` in Rego use the debug logger instead of stdout.
> Opa config

- .poutine.yml
- .poutine/config.rego
- models/config.go
- opa/capabilities.json
- opa/opa.go
- opa/opa_test.go
- opa/rego/poutine/config.rego
- opa/rego/poutine/queries/findings.rego
- opa/testdata/config/sample.rego
- add an option in models.Config to include additional local Rego files during compilation
- drop OPA capabilities and "pin" them by embedding a [capabilities.json](https://www.openpolicyagent.org/docs/latest/cli/#opa-capabilities) file 
- allow Rego modules in `data.poutine.config` to skip findings
> load additional Rego files

- cmd/root.go
cmd.Verbose isn't set yet in the Execute function it seems and verbose logging can't be enabled. I moved the call to set the log level after the config file parsing in initConfig and it worked :shrug: ~I'm not sure if there is somewhere else the logger should be initialized instead.~ Moved log initialization into the PersistentPreRun hook.
> fix: verbose log level

- analyze/analyze.go
- providers/github/client.go
Added Error that could indicate improper auth or a typo in the org name. Added skipping of printing the results if no findings are present
> Add Error for Empty Organization

- models/gitlab.go
- models/gitlab_test.go
```
git clone --depth=1 https://gitlab.gnome.org/GNOME/gimp.git
go run . analyze_local --scm gitlab gimp --format json | jq | grep include
```
now properly includes `pkg:gitlabci/include/remote?download_url=https%3A%2F%2Fgitlab.gnome.org%2FGNOME%2Fcitemplates%2Fraw%2Fmaster%2Fflatpak%2Fflatpak_ci_initiative.yml` in the build inventory
> gitlab: fix parsing error on scalar includes

- .github/workflows/pop.yml
You cannot have both `paths` and `paths-ignore`
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> Fix GitHub Action workflows paths / paths-ignore

- .goreleaser.yaml
Patch the critical/high CVEs in Git and others
> chore: upgrade base_image

- formatters/pretty/pretty.go
This updates the documentation links to use GitHub pages.
e.g., https://github.com/boostsecurityio/poutine/blob/main/docs/content/en/rules/debug_enabled.md -> https://boostsecurityio.github.io/poutine/rules/debug_enabled/
(Assuming that this is the intention behind the GH pages site.)
> Change doc links to GitHub pages

- analyze/analyze.go
- opa/models.go
- opa/rego/rules/debug_enabled.rego
- scanner/inventory_test.go
- scanner/testdata/.github/workflows/debug_enabled_valid.yml
In the `debug_enabled` rule:
- For GitHub Actions, report line numbers of the step or job that enables debugging. 
- Fix the `step` metadata value. It must be the step's index since the id is not always defined.
in analyze_org, log errors instead of cancelling the entire analysis of the org (see https://github.com/boostsecurityio/poutine/pull/102). Because of the wrong step reported in the `debug_enabled` rule, an org that had debugging enabled on a single workflow step could not be analyzed at all.  
Make it so `FindingMeta` parsing error are logged instead. Currently, if a finding with metadata that cannot be parse would crash the org's analysis with the following error:
```
12:55PM | ERROR | error="failed to analyze repo statusburger/actions: json: invalid number literal, trying to …
```
> fix debug_enabled on steps and error handling

- providers/github/client.go
This fixes #100.
**Query returns `null` (org does not exist)**
```sh
$ poutine analyze_org $org --scm github --token=...
Error: failed to analyze org $org: failed to get batch of repos: org does not exist
```
**Query returns 0 repos**
```sh
$ poutine analyze_org $org --scm github --token=...
12:16PM | INFO  | No repositories found for org. If this is unexpected, ensure your token has the correct permissions.
12:16PM | INFO  | No results returned by analysis
```
> Improve `GetOrgRepos` enumeration

- providers/gitops/gitops.go
This is a small cosmetic change to trim whitespace from Git command's Stderr output.
```
ERROR | failed to clone repo error="failed to clone repo: command `/usr/bin/git fetch --quiet --no-tags --depth 1 --filter=blob:none origin HEAD` returned an error: exit status 128 stderr: fatal: couldn't find remote ref HEAD\n" 
```
> Trim whitespace from Git errors

- formatters/pretty/pretty.go
This is a proposed change to improve the clarity of output. 
This fixes #99. (Need to write that for GitHub to link the issue.)
**Before**
```
Analyzing repositories  59% |███████████████████████                 | (22/37) [12s:6s]
Rule: CI Runner Debug Enabled
Severity: note
Description: The workflow is configured to increase the verbosity of the runner.
This can potentially expose sensitive information.
Documentation: https://boostsecurityio.github.io/poutine/rules/debug_enabled
No findings for this repository
Rule: Default permissions used on risky events
Severity: warning
Description: The workflow and some of its jobs do not explicitely define permissions
and the workflow triggers on events that are typically used to run builds from forks.
Because no permissions is set, the workflow …
```
> Only print rules with results

- providers/gitops/gitops.go
This is an admittedly paranoid change to ensure that `token` can't inadvertently be leaked in the output.
> Redact Git clone token in errors

- README.md
We've published to Homebrew Core now.
We will keep our local tap for now so that we can test both, but probably eventually drop the local tap.
Close #94
> Update README.md to refer to Homebrew core formula

- README.md
the tap migration would be handled by https://github.com/boostsecurityio/homebrew-tap/pull/1
> docs: cleanup up tap reference

- .goreleaser.yaml
We are archiving the tap since we've moved to official brew core
> Update .goreleaser.yaml - remove local tap publishing

- opa/opa_test.go
- opa/rego/rules/unverified_script_exec.rego
- scanner/inventory_test.go
- scanner/testdata/.github/workflows/valid.yml
- Add a rule to detect curl|bash and related patterns
- The rule is targeted to identify popular installation scripts that end up in workflows rather than all the possible ways a bash script can load external scripts.
- The rule considers scripts loaded from a commit sha on a GitHub repository to have been "verified"
- Add a test to validate that built-in rules have correct metadata for the SARIF level 
Docs will be in the next pr
> feat: add `unverified_script_exec` rule

- analyze/analyze.go
- cmd/analyzeRepo.go
- opa/rego/poutine/format/json.rego
This closes #125 by adding a `--ref` flag to `analyze_repo`.
It can be useful to test new changes before merging them to a default branch, or testing Poutine's capabilities against known vulnerable configurations that are no longer in `HEAD`.
> Specify custom ref with `analyze_repo`

- analyze/analyze.go
- cmd/analyzeLocal.go
- cmd/root.go
- formatters/json/json.go
- opa/rego/poutine/queries/format.rego
- providers/github/client.go
When using the JSON format, another OPA instance was created different than the one used to analyze the packages. This new OPA instance is not configured so the included Rego from the configuration cannot be used to define formats.
`analyzer.NewAnalyzer` now requires an OPA instance as argument.
This PR also modifies the behavior when running poutine with an unknown format. It used to silently fall back to the pretty format. It will now error out and list the available formats:
```
$ go run . analyze_local scanner/testdata -f asdf
Error: failed to analyze repoPath scanner/testdata: format asdf not found in the available formats: json, pretty, sarif
```
> fix: remove 2nd Rego compilation in json format, custom formats and validation

- opa/capabilities.json
Support for this capability was added in https://github.com/boostsecurityio/poutine/pull/48 but not exposed.
> opa: expose `json.marshal_with_options`

- analyze/analyze.go
- cmd/root.go
- models/config.go
- Fix #123
- Changed the `anlayze_repo` progress bar to provide progress on the git clone step and the analysis step. On big repos this helps showing that we're waiting for the git clone.
- Remove fmt.Println in analyze
- Enable auto clearing the progress bar when it's finished.
> feat: add `--quiet` option

- .github/workflows/release.yml
We've already removed the ref in the goreleaser
> Remove homebrew tap support

- .dockerignore
- .goreleaser.yaml
- Dockerfile
- add a dockerfile to more easily build a container with poutine without having goreleaser or ko
- the `base` target could be used in the future as a base image to address https://github.com/boostsecurityio/poutine/issues/78
- upgrade the base image to patch busybox CVEs
> chore: add dockerfile, upgrade git image

- opa/rego/external/build_platform.rego
- opa/rego/rules/known_vulnerability_in_build_platform.rego
- scanner/inventory_test.go
https://about.gitlab.com/releases/2024/06/26/patch-release-gitlab-17-1-1-released/#run-pipelines-as-any-user
adding this CVE uncovered the bug that `data.rules.known_vulnerability_in_build_platform.provider_advisory` crashes opa's evaluation when the SCM instance is affected by multiple advisories.
> add gitlab CVE-2024-5655

- dagger.json
- dagger/.gitattributes
- dagger/.gitignore
- dagger/go.mod
- dagger/main.go
Add a Dagger module to use poutine. I tried to recreate the CLI using Dagger's API as closely as possible.
It's convenient to have Dagger cache poutine's output and manage cloning git repository. For instance, running custom rules in boost-rnd/poutine-rules on actions/github-script can be done like so:
```
dagger -d call -m github.com/boostsecurityio/poutine@dagger \
--config-src https://github.com/boost-rnd/poutine-rules \
analyze-local \
--src https://github.com/actions/github-script
```
This module is already listed on the Dagger module registry and hopefully brings more visibility to the project.
> add Dagger module

- .poutine.sample.yml
- models/config.go
- opa/models.go
- opa/opa_test.go
- opa/rego/poutine.rego
- opa/rego/poutine/utils.rego
- opa/rego/rules/pr_runs_on_self_hosted.rego
- scanner/inventory_test.go
- scanner/scanner_test.go
- scanner/testdata/.github/workflows/allowed_pr_runner.yml
- extend the rule metadata schema to allow declaring rule-specific configuration options
- in the config file, rule configurations are placed in `rulesConfig`
- add the `allowed_runners` configuration option for `pr_runs_on_self_hosted` to fix #155
> feat: rules configuration for `pr_runs_on_self_hosted`

- models/azure_pipelines.go
- models/azure_pipelines_test.go
- models/package_insights.go
- opa/rego/poutine/inventory/azure_pipelines.rego
- opa/rego/rules/injection.rego
- opa/rego/rules/unverified_script_exec.rego
- scanner/inventory_test.go
- scanner/scanner.go
- scanner/testdata/.azure-pipelines.yml
- scanner/testdata/azure-pipelines-1.yml
- Initial support to parse Azure Pipelines. 
- Only the [pr](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines) field and [steps](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps?view=azure-pipelines) are modeled.
- Only a subset of files are considered as Azure Pipelines.
- No support for expressions. 
- Add rules in `unverified_script_exec` & `injection`  to analyze Azure Pipelines.
- The tasks used in a pipeline are reported in the build inventory using the purl type `pkg:azurepipelinestask`
> feat: Azure Pipelines

- scanner/scanner.go
- scanner/scanner_test.go
Simplifies parsing by walking files only once. Fixes #161
> Simplify Repo File Parsing

- README.md
- docs/content/en/rules/injection.md
- docs/content/en/rules/untrusted_checkout_exec.md
documenting Tekton and added section of supported platforms
> Add Pipelines As Code Documentation

- analyze/analyze.go
- providers/github/client.go
This ensures that the specified `--scm-base-url` is applied to both the REST and GraphQL clients.
> Fix GitHub client not respecting `--scm-base-url`

- analyze/analyze.go
- cmd/root.go
- models/purl.go
- models/purl_test.go
- providers/github/client.go
- providers/gitlab/client.go
- providers/scm/domain/scm_domain.go
- providers/scm/domain/scm_domain_test.go
This fixes #190.
Tested against an instance of GHES. It works for rules like "CI Runner Debug Enabled" and "Pull Request Runs on Self-Hosted GitHub Actions Runner" but not "GitHub Action from Unverified Creator used". That requires somehow passing the base domain to [`PurlFromGithubActions` and `PurlFromDockerImage`](https://github.com/boostsecurityio/poutine/blob/e259b09e5f955a241cb4510e8c188dbaa17292a7/models/purl.go#L62), which could be more complicated.
> Fix finding URL not respecting `--scm-base-url`

- analyze/analyze.go
- cmd/root.go
- opa/opa.go
- opa/opa_test.go
- scanner/inventory.go
- scanner/inventory_test.go
- scanner/scanner_test.go
Reworked analyze org to fix data race when accumulating scanned packages in the inventory to then proceed to the finalization of the analysis. Fixes #195 
Also reworked opa initialization. We initialize the opa compiler only once instead of every time the evaluation is called.
> Fix Analyze Org Data Race

- analyze/analyze.go
This fixes #191.
(Or it should, this is admittedly a drive-by change I haven't tested.)
> Gracefully skip empty repos

- opa/rego/rules/untrusted_checkout_exec.rego
- Adds `pip` commands 
- Code execution can be achieved via [`setup.py`](https://docs.python.org/3.11/distutils/setupscript.html) script after installing
- Adds `cargo` commands 
- Code execution can be achieved via [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) scripts which are invoked before build
> feat(rules): additional code execution commands for untrusted checkout exec

- providers/local/client.go
When testing against local repos, some rules may refer to `default_branch` which was set to empty string. We set a reasonable default value of `main`.
> Set default Git branch for analyze_local

- cmd/root.go
- models/config.go
- opa/opa.go
**Feat: Add `--skip` CLI option and optimize skipped rule processing**
This PR introduces two key improvements:
1.  **New `--skip` Command-Line Option:**
* Allows users to specify a list of rule IDs (e.g., `--skip rule1,rule2`) to be skipped during execution.
* These rules are added to any rules already skipped via the configuration file.
* This provides a convenient way to disable entire rules directly from the command line, overriding any partial skips defined in the configuration for the same rule ID (i.e., if partially skipped in config but fully skipped via CLI, the rule is fully skipped).
2.  **Performance Optimization for Skipped Rules:**
* Previously, all rules were processed/compiled, and their results were filtered afterwards according to the skip configuration.
* This change …
> Optimize skip rule

- .poutine.sample.yml
- cmd/root.go
- models/config.go
- opa/opa.go
New option to include only a set of rules via the CLI or config file. This is compatible with the existing skip option, since the skip options can be use to filter more specific results. If includes rules is empty, it is ignored.
> Add include option to CLI and config file

- README.md
Hello !
I saw your presentation at NorthSec and thought I would try poutine !
I just noticed a small typo in the README, hope this helps !
> Fix typo in README: --scm-base-uri --> --scm-base-url
